import React, { useState } from 'react';
import { ShieldIcon } from '../components/Icons';
const labels = { CONFIRMED_ISSUE: 'Confirmed issue', FALSE_POSITIVE: 'False positive', NEEDS_DOCUMENTS: 'Needs documents', RESOLVED: 'Resolved' };
export default function ManagerReviewView({ cases = [], onReview }) {
  const [notes, setNotes] = useState({}); const [status, setStatus] = useState({});
  return <div className="view-wrap"><div className="page-heading-row"><div><h1 className="page-title">Manager Review Queue</h1><p className="page-subtitle">High-risk audits and SLA-delayed cases requiring a manager decision.</p></div><span className="status-summary"><ShieldIcon size={16} /> {cases.length} open case{cases.length === 1 ? '' : 's'}</span></div>
    {cases.length === 0 ? <div className="card empty-state"><div className="empty-state-msg">No cases need manager review</div><div className="empty-state-sub">Flagged comparisons and delayed automations appear here.</div></div> : <div className="manager-case-grid">{cases.map(item => { const id = item.complaint.id; const current = status[id] || item.comparison?.reviewStatus || 'UNREVIEWED'; return <div className="card" key={id}><div className="card-header"><div><div className="vehicle-code">{item.complaint.vehicleNumber}</div><span className="card-subtitle">{item.customer?.name || 'Customer'} · {item.customer?.serviceCenter || item.customer?.service_center}</span></div><span className={`badge ${item.slaDelayed ? 'badge-coral' : 'badge-amber'}`}>{item.slaDelayed ? `SLA DELAY · ${item.ageMinutes} min` : `${item.comparison?.score ?? '—'}% SCORE`}</span></div><p className="match-analysis">{item.comparison?.summary || 'Automation is still waiting for the required information or processing step.'}</p><div className="form-group"><label className="form-label">Manager decision</label><select className="form-select" value={current} onChange={e => setStatus({ ...status, [id]: e.target.value })}><option value="UNREVIEWED" disabled>Choose a decision</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="form-group"><label className="form-label">Review notes</label><textarea className="form-input" style={{ minHeight: '76px' }} value={notes[id] ?? item.comparison?.reviewNotes ?? ''} onChange={e => setNotes({ ...notes, [id]: e.target.value })} placeholder="Reason, action, or requested documents" /></div><button className="btn btn-primary btn-full" disabled={current === 'UNREVIEWED'} onClick={() => onReview(id, current, notes[id] ?? item.comparison?.reviewNotes ?? '')}>Save manager decision</button></div>; })}</div>}
  </div>;
}
